---
- name: Install required system packages
  yum:
    pkg:
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker Repository
  yum_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update yum and install docker-ce
  yum:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker
