---
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  yum_repository:
    name: docker-ce-stable
    async: yes # not required. If set to C(yes) Yum will download packages and metadata from this repo in parallel, if possible.
    file: docker-ce
    base_url: "{{ docker_repo }}"

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
