---
- name: "Check if docker-ce file exists"
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: stat_result
- block:
    - name: "Make sure yum-utils pkg is installed"
      dnf:
        name: yum-utils
        state: latest
    - name: "Install the Docker Community Edition Repository"
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      register: ycm
    - name: "Enable and run Docker CE"
      service:
        name: docker
        state: started
        enabled: yes
  when: not stat_result.stat.exists
